spring:
  datasource:
    url: jdbc:h2:mem:codex
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: verySecretPhrase
  header: Authorization
  expiration: 3000000

admin:
  email: rdejozxxgbryoaonvc@mhzayt.online

email:
  username: springboottestsamplemail@gmail.com
  password: VeryHardPassword123
